format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_PIC32MX1/2/5_Starter_Kit, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '36', y: '71', id: BSP_PIC32MX1/2/5_Starter_Kit}
