configName: pic32mx_125_sk
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32MX570F512L
projectName: ''
settings:
  PackageFilter: audio;bootloader;bootloader_apps_uart;bsp;bt;core;core_apps_pic32mx;crypto;csp;csp_apps_pic32mx;gfx;reference_apps;net;quick_docs;touch;usb;wireless;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MX_DFP\1.4.241\atdf\PIC32MX570F512L.atdf
